Added missing NetworkId to ParticipantData Packet and added toString function for some types
anilmisirlioglu/f1-telemetry-go pull request #7
Opened 2022-02-22 17:18 UTC by derSoerrn95

2022-02-22 18:20 UTC, anilmisirlioglu requested changes

2022-02-22 18:20 UTC, anilmisirlioglu commented on pkg/env/team/constants.go
> +type TeamsType uint8
It would be better to rename it to `Team`

2022-02-22 18:20 UTC, anilmisirlioglu commented on pkg/env/session/constants.go
> +var sessionNames = map[SessionType]string{
It would be better to rename it to `sessions`

2022-02-22 18:20 UTC, anilmisirlioglu commented on pkg/env/driver/constants.go
> +var driverNames = map[DriversType]string{
It would be better to rename it to `drivers`

2022-02-22 18:20 UTC, anilmisirlioglu commented on pkg/env/driver/constants.go
> +type DriversType uint8
It would be better to rename it to `Driver`

2022-02-22 18:20 UTC, anilmisirlioglu commented on pkg/env/team/constants.go
> +var teamNames = map[TeamsType]string{
It would be better to rename it to `teams`

2022-02-22 18:20 UTC, anilmisirlioglu commented on pkg/env/track/constants.go
> +type TrackType uint8
It would be better to rename it to `Track`

2022-02-23 15:21 UTC, derSoerrn95 commented
✅

2022-02-23 15:53 UTC, anilmisirlioglu commented
Thanks :)

2022-02-23 15:53 UTC, merged

2022-02-23 16:14 UTC, derSoerrn95 commented
you're welcome :)